repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: detect-private-key
    -   id: check-shebang-scripts-are-executable
    -   id: check-case-conflict
    -   id: check-added-large-files
        args: ['--maxkb=16384']
  - repo: https://codeberg.org/frnmst/md-toc
    rev: '8.1.9'
    hooks:
    - id: md-toc
      args: [-p, 'cmark', '-l6']
  - repo: https://github.com/jorisroovers/gitlint
    rev: 'v0.18.0'
    hooks:
    - id: gitlint
